name: Publish jar to Maven Central

on:
  push:
    branches:
      - master
      - hotfix/fix-release

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:


      - name: Decode the signing key
        run: echo "ORG_GRADLE_PROJECT_signingKey='$(echo $ORG_GRADLE_PROJECT_SIGNINGKEY_BASE64 | base64 --decode)'" >> $GITHUB_ENV
        env:
          ORG_GRADLE_PROJECT_SIGNINGKEY_BASE64: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY_BASE64 }}

      - name: Logging
        run: echo ${{ env.ORG_GRADLE_PROJECT_signingKey }}

      - name: Publish image
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
        with:
          gradle-version: wrapper
          arguments: |
            publishAllPublicationsToSonatypeRepository
            closeAndReleaseRepository
