name: Pull request

on:
  pull_request:
    branches:
      - develop

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with gradle
      uses: gradle/gradle-build-action@v2
      env:
        HARVEST_ACCOUNT_ID_ADMIN1: ${{ secrets.HARVEST_ACCOUNT_ID_ADMIN1 }}
        HARVEST_AUTH_TOKEN_ADMIN1: ${{ secrets.HARVEST_AUTH_TOKEN_ADMIN1 }}
        HARVEST_ACCOUNT_ID_ADMIN2: ${{ secrets.HARVEST_ACCOUNT_ID_ADMIN2 }}
        HARVEST_AUTH_TOKEN_ADMIN2: ${{ secrets.HARVEST_AUTH_TOKEN_ADMIN2 }}
      with:
        gradle-version: wrapper
        arguments: build

    - name: Generate test coverage report
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: jacocoTestReport

    - name: Upload report to codecov.io
      run: |-
        echo "Uploading report..."
        bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/test/jacocoTestReport.xml

    - name: Save test results
      run: |-
        echo "Saving test results"
        mkdir -p ~/junit/
        find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
